### ISSUE TITLE
Sample document for table testing.

### ISSUE THREAD

**Issue by wendellpiez** [wendellpiez/JATSKit#15]
Two of the document types formally supported by the framework (and several more that are informally supported) permitted a JATS-defined close variant of the OASIS table model, which is to say an updated and slightly refined subset of a CALS/Docbook table model.

Additionally, all of the models also support an HTML-flavored table model.

A sample document https://github.com/wendellpiez/JATSKit/blob/develop/samples/pathological-blue.xml contains a couple of tables, both HTML and CALS/OASIS, and is suitable as a testbed for table-related functionality (as for other things).

Other frameworks in oXygen (notably Docbook and HTML) have a great deal of table-processing logic that could perhaps be adapted for JATS/BITS. Actions for table manipulation can be bound to buttons and menu items. In some cases this may be as simple as calling their .jar files in and using their APIs. In others there will have to be changes in the Java since although logic is the same, names are different (e.g. Docbook 'entry' vs JATS 'oasis:entry' as the name of an element.).

This also goes for testing things like the OASIS table Schematron checks I plan shortly to install ...

**Comment by raducoravu** [comment]
> This also goes for testing things like the OASIS table Schematron checks I plan shortly to install ...

Actually Oxygen 18 will also have support to validate OASIS tables as a separate validation step which can be chosen in the validation scenario, but we have not tested it with JATS, I will try to make some time to test it with JATS. Originally we also wanted to do this using Schematron but we decided to go with custom Java processing which is lighter, it reacts on SAX events and does not load the entire XML in memory.

**Comment by wendellpiez** [comment]
Radu, yes, doing this in XSLT was an instructive exercise -- and it fell out naturally from table-rendering logic (so it wasn't even very hard to put it into Schematron) -- but it definitely makes sense to have the Java handle OASIS table validation. (Meanwhile we can use the validators to cross-check one another?)

**Comment by raducoravu** [comment]
We now have actions to insert HTML tables and to manipulate them by adding/removing rows/columns, splitting and joining cells. There is no CALS table support yet, we'll maybe do that on another issue if somebody asks for this.
