### ISSUE TITLE
Icons for Actions

### ISSUE THREAD

**Issue by wendellpiez** [wendellpiez/JATSKit#17]
Maybe there are icons we can find somewhere (in an open-source framework library or collection?) for the Actions I have included in the base framework, for inserting MathML, boxed text and one or two items ... presently these show in the Toolbar as buttons with text labels.

Any tips on where to find a library of free-to-use icons?

**Comment by raducoravu** [comment]
So we need icons for:

1) Insert MathML equation. We already have this in the oxygen.jar, you can refer to it from the action with "/images/Equation24.png"
2) Monospaced 
3) Boxed text
4) Display quote
5) Code

I'll also ask our designer if he has some time to look at what it would take to design the others. We are getting close to releasing 18.0 so not sure but he might have quite some workload right now.

**Comment by wendellpiez** [comment]
Yes, plus whatever other Actions we come up with!

For example an "insert Equation" that would insert a <formula> or <inline-formula> wrapper around MathML ... (I think this goes on that other issue.)

**Comment by raducoravu** [comment]
I committed and connected the icons our web designer worked on. Hopefully that's OK.
