### ISSUE TITLE
Schematron Quickfix test

### ISSUE THREAD

**Issue by wendellpiez** [wendellpiez/JATSKit#18]
For whatever reason, the Schematron Quickfixes in the two Schematron files inside lib/Schematron are not working.

For example at https://github.com/wendellpiez/JATSKit/blob/develop/lib/Schematron/jatskit-QA.sch

I have double-checked namespaces but there's something missing. Perhaps not in the Schematron file itself. What would disable QuickFixes? (oXygen 17.1. And I looked at the panel under Options/Preferences.) This can be tested by binding the Schematron to the document by hand or by using a Validation Scenario in the editor.

The QuickFix I have (in the file cited) is supposed to add an @id to any of certain element types, which do not have one (matching '\S').

**Comment by raducoravu** [comment]
The main problem is that the assert needs to point to the quick fix:

    <sch:assert test="matches(@id,'\S')" role="warning"  sqf:fix="add-id">Missing @id</sch:assert>

**Comment by raducoravu** [comment]
You should probably also remove the @select attribute from the add:

        <sqf:add node-type="attribute" target="id" select="@id">
          <sch:value-of select="$user-id"/>
        </sqf:add>

**Comment by wendellpiez** [comment]
I knew it had to be something like that but it was getting late. Thanks!
