### ISSUE TITLE
Bug in insert.graphic Action

### ISSUE THREAD

**Issue by wendellpiez** [wendellpiez/JATSKit#19]
For whatever reason I can't seem to get the insert.graphic Action (invoked via button) to work directly in the context of 'fig', where the element 'graphic' is permitted. It wants to insert 'inline-graphic' and it can't due to its being invalid.

We may wish to consider separate actions for (a) inserting single graphics (either 'graphic' or 'inline-graphic') depending on context, and (b) for inserting 'fig' elements with graphics and (optionally) captions.

```
<fig>
   <caption>
     <title>A Figure</title>
  </caption>
  <graphic xlink:href="..."/>
</fig>
```

**Comment by raducoravu** [comment]
The problem is in the Java operation, I comitted a fix for it.
