### ISSUE TITLE
Broken github setup

### ISSUE THREAD

**Issue by wendellpiez** [wendellpiez/JATSKit#21]
Hi,

For whatever reason, it no longer works to point to https://github.com/wendellpiez/JATSKit/raw/develop/oXygenJATSframework.xml from the **Add-ons** panel under **Options / Preferences** in oXygen. Nothing happens when I select Apply, and the framework does not load.

I can, however, see the zip file at https://github.com/wendellpiez/JATSKit/archive/develop.zip as referenced.

But I seem to have broken the framework xml file somehow. (Radu, any idea?)

Thanks, Wendell

**Comment by raducoravu** [comment]
My colleague Alex will look into this today and add his analysis results here.

**Comment by AlexJitianu** [comment]
Hello,

Adding the URL inside preferences is just the first step. Afterwards you have to manually install the add-ons, from the Help menu using the "Install new  add-ons..." action.

Which Oxygen version are you using? Anyway, in the later versions of Oxygen you don't have to go to Preferences at all. Just go directly to Help->"Install new add-ons..." and paste that URL inside the text field on the upper part of the dialog. The two frameworks will appear (JATS and JATSKit) and you can proceed with their installation.

Best regards,
Alex

**Comment by wendellpiez** [comment]
Alex helped me out ...
