### ISSUE TITLE
Several possible issues

### ISSUE THREAD

**Issue by raducoravu** [wendellpiez/JATSKit#24]
1) Rename the project, right now it has JATS 1.0 in its name.
2) Modify the readme to also state JATS 1.1 instead of 1.0.
3) There is a templates folder on disk called "templates/bits" but the bits.framework is referencing to it like "templates/BITS", meaning that the new file template will not be available when working on Linux which is case sensitive.

**Comment by raducoravu** [comment]
@wendellpiez I did (2) and (3) but I do not have access rights to do (1). 
Also not sure if for (2) I need to do something else.

**Comment by wendellpiez** [comment]
Radu, as usual I am being a dimwit, but to which project name do you refer? I think we did all this ... feel free to reopen if not.

**Comment by raducoravu** [comment]
So on this page:

https://github.com/wendellpiez/JATSKit

the description of the project is:

     oXygen XML Editor framework for NISO JATS 1.0 / NLM BITS

**Comment by wendellpiez** [comment]
I think  I managed it this time thanks Radu!

**Comment by raducoravu** [comment]
:+1:
