### ISSUE TITLE
Make keyboard shortcuts platform independent

### ISSUE THREAD

**Issue by raducoravu** [wendellpiez/JATSKit#27]
Keyboard shortcuts for some actions (3-4 actions) like "Monospace" are using platform dependent shortcuts like "CTRL M". This means that on Mac OSX it will not work as expected (using COMMAND M).
When you define a shortcut for an action you can check a checkbox to make it platform independent.

**Comment by wendellpiez** [comment]
Thanks for noticing this I made some changes.
