### ISSUE TITLE
Reconsidering fallback bindings

### ISSUE THREAD

**Issue by wendellpiez** [wendellpiez/JATSKit#33]
Now it's been a few months living with the "tighter" bindings (JATSKit now "turns on" only for documents with the latest FPIs) I am thinking we can loosen them up again, thereby providing JATSKit functionality back to older NLM DTD variants. It would probably do no harm if we do it right. And even if the current codebase isn't tested against (structures only in) the older DTDs, most things should still work.

Maybe something like an Association Rule in the base JATSKit framework -- whose priority should be Lowest in oXygen -- that matches it to either "NLM DTD" or "NISO Z39.96-2015" in a document's FPI. that should catch just about everything.

Note that as delivered right now, all the frameworks have Priority Setting Low -- the base framework is non-operational only because it doesn't match anything. (It is only a template.) If it also going to be the "fallback" framework for documents that appear NLM-like (by FPI) -- it should be set to Lowest.

**Comment by raducoravu** [comment]
👍 I agree the base framework could catch most NLM DOCTYPE cases. Also you are right about lowering its priority for it to become a fallback for all others.

**Comment by wendellpiez** [comment]
I *think* all the DTDs back to the earliest versions have been assigned Formal Public Identifiers that start either

```
-//NLM//DTD JATS
```
or (recently)
```
-//NLM//DTD BITS
```
Is there a way to bind a document by virtue of a call to an FPI containing either substring? This might cover DTDs back all the way to v1.0 (I'm looking into this).

From what I can see, the Association Rules in oXygen supports wildcards, but not regex.

Note the proposal is not to include copies of all the DTDs in the framework, but only to make framework components available to users who have otherwise bound their (older) DTDs, and wish to use the XSLTs etc.

**Comment by wendellpiez** [comment]
With help from https://github.com/JATS4R/validator/blob/master/jats/jats.yaml (thanks for the tip Alf) I can see this won't work - the 'JATS' substring came into use only with the NISO versions.

The only common matching substring appears to be "-//NLM//DTD" and that seems awfully broad.

**Comment by raducoravu** [comment]
We do not support full regexp in the association rules fields. Most users would not know how to compose regexp expressions but wildcard-based matches are easy to understand.

**Comment by wendellpiez** [comment]
Thanks Radu. Since it turns out the FPIs are even less consistent than I had hoped, I think we'll end up with matching on "-//NLM//DTD*" i.e. a wildcard match (I think this will work right?). (I didn't actually think regex would work :wink: but the docs didn't appear to say much one way or the other.)

There may be a chance around the edges that matching  "-//NLM//DTD*" will make false hits, if there are any DTDs at NLM that are not the NCBI 'journal article' DTD and its spinoffs -- and have an FPI that says so.

So there may be a little more research for me to do but we have a provisional answer, I think. (Issue closed with my thanks.)

(Maybe some day oXygen's Association Rules could have an "Advanced" panel allowing finer control of document matches? for you guys to think about.)

**Comment by wendellpiez** [comment]
Arg, Alf @hubgit confirms that NLM also has "-//NLM//DTD PubMed 2.5//EN" -- and undoubtedly others -- which would be wrongly matched.

Either we have to force users to tolerate / debug these (bad idea), or make/find a better way to match. (Maybe the Java option?)

**Comment by wendellpiez** [comment]
Actually I don't think it's that bad, I think there are a few options...

**Comment by raducoravu** [comment]
{quote}(Maybe some day oXygen's Association Rules could have an "Advanced" panel allowing finer control of document matches? for you guys to think about.){quote}

We'll keep this in mind.

{quote}Either we have to force users to tolerate / debug these (bad idea), or make/find a better way to match. (Maybe the Java option?){quote}

Sure, the custom rule matcher implementation would give you full access to the document's public and system IDs, to its root element name and attributes.

**Comment by wendellpiez** [comment]
The most recent commit reduces the frameworks back to a single framework to match any/all JATS/BITS including legacy NLM formats. (In the `develop` branch until we merge.)
