### ISSUE TITLE
row separator priority

### ISSUE THREAD

**Issue by bkeithrose** [wendellpiez/JATSKit#37]
Hi Wendell, found an issue with p:border-spec function within oasis-table-normalize.xsl. The top and bottom variables were ranking <colspec> value of @rowsep above a value specified by <row>.

These two lines seem to render proper borders:

    <xsl:variable name="top" select="(($neighbor-up/@rowsep, $neighbor-up/parent::row/@rowsep, 
      $neighbor-up/p:colspec-for-entry(.)/@rowsep, $entry/ancestor::tgroup[1]/@rowsep, $entry/ancestor::table[1]/@rowsep)[1] = '1')
      or ($top-edge and $frame-spec=('top','topbot','all'))"/>
    
    <xsl:variable name="bottom" select="(($entry/@rowsep, $entry/parent::row/@rowsep, 
      $entry/p:colspec-for-entry(.)/@rowsep, $entry/ancestor::tgroup[1]/@rowsep, $entry/ancestor::table[1]/@rowsep)[1] = '1')
      or ($bottom-edge and $frame-spec=('bottom','topbot','all'))"/>

**Comment by wendellpiez** [comment]
@bkeithrose thanks for bringing my attention to this. Only in the real world could you find something like it. Please make me a PR. In a perfect world, this repo also would have a place to put a demonstrating example, but maybe we can manage that out of band.

**Comment by bkeithrose** [comment]
Yep - I think I created a PR from a fork I just created this evening.  Hopefully I did it right.  I agree - it would be nice to attach examples/test cases.  Maybe you can, but I am no GitHub expert.

**Comment by wendellpiez** [comment]
We should probably make a subdirectory to drop that stuff into. But that would alas require more organization than I am able to provide. Meanwhile thanks for debugging and correcting this we are all indebted.

**Comment by wendellpiez** [comment]
@bkeithrose you probably saw PR #38 thanks! I never would have found this much less have known what to do about it. (That might sound odd but it is true. There is nothing like experience in the field.) 👍 from me. There must be more such errors: whatever you find could be repaired in similar fashion.
