### ISSUE TITLE
Allow configuring fonts for publishing

### ISSUE THREAD

**Issue by raducoravu** [wendellpiez/JATSKit#41]
https://www.oxygenxml.com/forum/viewtopic.php?f=1&t=21567

       I live in Slovenia where we use some scaron signs like "ŠĐČĆŽ - šđčćž". I noticed that when I convert the XML to "JATS/BITS single HTML page" all letters are displayed just fine.
       But when I try to generate the "JATS/BITS PDF preview", just letters Ž and Š are displayed ok, but letters Č and Ć aren't ok. If I try to insert a string like "ŠĐČĆŽ šđčćž" it looks then like this:
     PDF version: Š###Ž š###ž (not ok)

At least define in the XSLTs the "titlefont" and "textfont" variables as xsl:parameters in order to be accessible when editing an XSLT transformation scenario from Oxygen in the "Parameters" list.

**Comment by raducoravu** [comment]
Also the attribute set for "paragraph" should probably use the attribute set for "sans-serif" which in turn should use the $textfont in order to be able to configure all the fonts using two parameters:

    <xsl:attribute-set name="sans-serif">
      <xsl:attribute name="font-family"><xsl:value-of select="$textfont"/></xsl:attribute>

**Comment by raducoravu** [comment]
@wendellpiez I added more fallback fonts to this XSL stylesheet: https://github.com/wendellpiez/JATSKit/blob/master/lib/xslt/jats-xslfo.xsl
They are the same fallback fonts we use for DITA publishing to PDF.

**Comment by wendellpiez** [comment]
@raducoravu awesome no PR necessary?

**Comment by raducoravu** [comment]
@wendellpiez sorry, I wanted Tomaz's input and I thought it would be faster if he would re-install the add-on. I will revert this if we encounter any problem. I added a default font on the entire fo:root element because for paragraphs it was not explicitly specified and it probably defaults to Helvetica in this case.

**Comment by wendellpiez** [comment]
No prob @raducoravu if you're comfortable I'm comfortable.

**Comment by futurion** [comment]
@raducoravu I can confirm, the PDF transformation now works perfectly with our UTF-8 signs I think this issue can be closed now.

**Comment by raducoravu** [comment]
@futurion great, thanks. 
@wendellpiez was this XSLT which I modified originally created by you or was it obtained from another project?
Initially in the XSLT the font families were specified as "serif" and "sans-serif" but as far as I know in the XSL-FO you need to add explicit references to existing font names, otherwise the Apache FOP falls back to Helvetica, which it did. Should I leave the fix as it is or do you have other improvement ideas?

**Comment by wendellpiez** [comment]
@raducoravu, the XSLT is minimally revised from an XSLT that Mulberry was contracted to write for NIH/NCBI, in the public domain (and perhaps still on their site). However, I wrote that XSLT too.

In any case, I think the ideal solution would be to expose a named (pair or set) of parameters for font settings, which can be modified per environment or publication. Such a pair could be `$header-font-family` set to 'sans-serif', `$body-font-family` set to 'serif', etc. Perhaps a `$label-font-family` to be used in generated labels.

As for XSL-FO, the spec is here: https://www.w3.org/TR/2001/REC-xsl-20011015/xslspec.html#font-family -- as you can see it's basically borrowed from CSS. Our problem is that while in theory, there should be support for generic family names such as "serif" and "sans-serif", FOP is not entirely conformant, so a separate analysis must sometimes be done to determine the best approach for FOP.

In any case it would be great if users could wire in their own font (families). I probably didn't include this feature since I didn't want the XSLTs to be too parameter heavy. (Also I had scoped the job specifically to 'preview', to help manage the functional requirements for production.) However, these days we could expose these settings in any number of ways (runtime lookup file instead of or in addition to `/*/xsl:param`?), so it's really a matter of what's the biggest benefit for the least effort, for users, defining "user" as either/both end users or developers, as appropriate.

**Comment by raducoravu** [comment]
I confirm from what I looked in the FOP code that it approximates "sans-serif" with "Helvetica" without any fallback font. And words like "določanje" are not rendered by default with Helvetica. I tested with Antenna House and it is somehow able to render the character with the default fonts. So there is a difference in implementation.
How about if I revert the XSLT fix (except the part where I set the body font to the fo:root which in my opinion is useful to have a font context for everything else), convert the "titlefont" and "textfont" variables to parameters, and leave them with the generic font names serif and sans-serif? Then I edit the Oxygen transformation scenario and in the Parameters list I set  values to those parameters so that everything works ok with FOP (in my opinion few people using JATS will ever invest in a commercial PDF processor).
By the way, and maybe @futurion could also help me with this why would someone publish JATS to PDF? Just to check how the content looks like? Do they submit the PDF somewhere? I guess I still do not know much about the ecosystem.

**Comment by wendellpiez** [comment]
That sounds like a good plan, and @futurion can try passing in fonts that can actually handle modern European languages, to test.

I'm not sure the JATS people will never use a commercial PDF processor ... even if I agree that (bottom line) if the XSL doesn't work tolerably well in FOP (with its shortcomings), it's not much use in an open-source offering like the JATSKit or even a commercial offering used mainly by devs, such as oXygen. (AntennaHouse is smart enough about its fonts to do substitutions when it has to. It probably has very neutral Unicode-complete fonts to fall back to in both serif and sans.)

But I too would be interested in the questions you pose @futurion. PDF *is* used as an ingest format, terrible as that sounds.

"I always knew I was going to be someone. Then I figured out I had to be more specific." (Lily Tomlin)

**Comment by futurion** [comment]
The JATS -> PDF transformation in Oxygen is actually useless for me and it only serves as preview for testing purposes how the output looks like. It's actually just a different "Author mode" output, similar to HTML output. I just noticed that some fonts weren't rendered ok as non-UTF8 font was initially used, so I mentioned the issue, nothing more.

Also, I am of course willing to do some extra tests with our special european texts which feature extra non-english characters, but again, we actually always stick to UTF8 fonts which feature completely all characters we use here so any UTF8 font is usually good choice and I believe there won't be any further issues if one is used.

**Comment by wendellpiez** [comment]
Awesome, thanks @futurion.

Your use of the PDF production is in accord with the design intentions -- the expectation being that for actual production you will want to do much more customizing than a generic toolkit can reasonably do (or it won't be generic). That you use it at all, indeed, is somewhat nice to hear.

By all means let's make the fonts switchable so it is at least useful for preview/proofing sorts of purposes.

**Comment by raducoravu** [comment]
@wendellpiez I opened a pull request.

**Comment by wendellpiez** [comment]
@raducoravu Cool, thanks! Do we not want a final fallback to 'serif' for `$titlefont` and 'sans-serif' for `$textfont`? Let me know if you think this is unnecessary (even for the 0.1% case) or unwise.

**Comment by raducoravu** [comment]
@wendellpiez I looked for inspiration at how DocBook does things, they have in the XSLT:

    <xsl:param name="body.font.family">serif</xsl:param>

it can be set externally and it's used directly further on in the XSL-FO. So I think we are Ok with the user having full control over the font family without us adding an extra fallback at the end just in case.

**Comment by wendellpiez** [comment]
Heh - what I'm realizing is that (in FOP at least) 'serif' and 'sans-serif' fail the test of being safe generic fallbacks - at least for anyone who wants practical access to Unicode (at least).

**Comment by raducoravu** [comment]
@wendellpiez right, anyway, I'll close the issue for now.
