### ISSUE TITLE
Cannot properly validate XML docs with a certain DOCTYPE

### ISSUE THREAD

**Issue by raducoravu** [wendellpiez/JATSKit#42]
If I have an XML file with this DOCTYPE:

     <!DOCTYPE article PUBLIC "-//NLM//DTD JATS (Z39.96) Journal Publishing DTD v1.1 20151215//EN" "http://jats.nlm.nih.gov/publishing/1.1/JATS-journalpublishing1.dtd">
<article xmlns:xlink="http://www.w3.org/1999/xlink" dtd-version="1.1" article-type="book-review" xml:lang="eng">

1. The ""-//NLM//DTD JATS (Z39.96) Journal Publishing DTD v1.1 20151215//EN"" public ID is not mapped to any DTD, the jats-catalog.xml has a commented out reference to a missing DTD
2. The jatskit-catalog.xml also has commented out references to "-//NLM//DTD JATS (Z39.96) JATS DTD Suite MathML Setup Module v1.1 20151215//EN" and a missing "JATS-mathmlsetup1.ent" which seems to be found in the ZIP file:
ftp://ftp.ncbi.nlm.nih.gov/pub/jats/publishing/1.1/JATS-Publishing-1-1-MathML2-DTD.zip

@wendellpiez should I update the jatskit-catalog.xml, un comment the inactive mappins and add the missing DTDs? Or is there a reason why the DTDs are not there in the first place?

**Comment by wendellpiez** [comment]
@raducoravu sure, feel free to make any updates that seem reasonable especially from a users' point of view. Thanks!

**Comment by wendellpiez** [comment]
Possibly the expectation would be that schema bindings would be done always through the framework and that a local catalog could override the framework catalog for special cases....

**Comment by raducoravu** [comment]
@wendellpiez I added a pull request with 4 more DTDs and two uncommented mappings in the catalog file. If you agree you can accept it and I will close this issue.
