### ISSUE TITLE
Rendering problems

### ISSUE THREAD

**Issue by raducoravu** [wendellpiez/JATSKit#46]
As a side effect of #5 there seem to be various rendering problems, elements like "date" have an imposed size, the font sizes are larger in the Author mode.

**Comment by futurion** [comment]
Also, all metadata details from <front> are rendered completely different, all references in <back> section have unreadable output, most of other text elements (titles, text, bullets, images) also don't display as expected.

With original JATSKit version (embedded in oxygen 22.1) these are no such issues, all rendered output in author mode is fine.

**Comment by raducoravu** [comment]
@futurion I will need some screenshots or small examples for each of the extra problems you found, I would need to know for each of the problems how the initial XML tags look like, how the Author mode looked like before and how it looks like now.

**Comment by futurion** [comment]
@raducoravu I prepared one pretty decent XML example with some taken screenshots from original and github version and I sent it over via email to you. You can test the included .xml file on both (embedded and github) version of JATSKit, the differences in layout are evident as the layout is completely different. All in all, the previous layout was way more clear and if it's an option to stay that way, I'd recommend that.

**Comment by raducoravu** [comment]
Thanks for the samples, we'll take them into account and get back to you after we make the changes.
Our initial purpose in #5 was to support tables editing but somehow the implementation of tables editing and the CSSs update were done kind of the same time and were difficult to separate from one another, so we updated the CSSs on the same issue.

**Comment by wendellpiez** [comment]
Ouch! 😉

**Comment by raducoravu** [comment]
We'll try to do a pull request fixing certain CSS changes before our November Oxygen 23 release. I think some of them are Ok, like removing some explicit background colors for elements, but others, like declaring certain elements as blocks, make the layout look bad. It's a problem of us not knowing enough of how the vocabulary should be used, but the samples @futurion provided will help.

**Comment by wendellpiez** [comment]
@raducoravu so the CSS goes back even farther than the XSL-FO, but I can try to help if you have questions particularly JATS questions. (Even those I am not absolutely up to date on ... but I know where to ask.) Thanks for all the support!

**Comment by raducoravu** [comment]
@wendellpiez @dumitrubogdanmihai just opened a pull request to fix the CSS-related problems:
https://github.com/wendellpiez/JATSKit/pull/48
Maybe you can take a look at it when you have some time.

**Comment by raducoravu** [comment]
@futurion would you be interested in uninstalling the add-on in Oxygen and re-installing it again from this project?
Maybe you can give us more feedback on the latest CSS changes which have just been accepted.

**Comment by futurion** [comment]
@raducoravu I did the comparison between both versions and I also prepared 5 screenshots from original and from new github version. Generally, it looks much better than initially, there's just two things I'd still like to point out.

1.) Fonts are (in my opinion) maybe still a bit too big... is there maybe an option to manually change font-size somehow?

2.) The viewport in original version is much wider (as wide as the screen is), while in the new version the viewport is really small. It seems as it's fixed to some certain width (maybe 1200px or something?). The width then affects every single element (text, blocks, tables, references, etc.). Also all text lines break too soon, there could be a lot more text in one single line in my opinion. Is there an option maybe as well to set the width of that viewport to full screen as in original?

However, all the differences are clearly visible in attached zip screenshots. I just sent them to you privately as there's some private journal content inside.

**Comment by raducoravu** [comment]
@wendellpiez  my coleague @dumitrubogdanmihai  added another PR for the second batch of problems: #49

**Comment by raducoravu** [comment]
@futurion it would be great if you could also test these latest CSS changes by uninstalling and then installing back the add-on.

**Comment by futurion** [comment]
@raducoravu I checked the latest version and I have to say it's a big improvement. More or less all elements now look nice, font is smaller which is also great and the best addition is that full width option. Really useful!

However, I'd still like to point out two things:

1. JATS uses two types of citations, which are mixed-citation and element-citation. It seems references in mixed-citation format are displayed ok in Author mode, while references in element-citation mode are not displayed ok.

2. Maybe there's still some room for Author mode display improvements for article meta data (journal-meta, article-meta). Now they're just in plain clear-text format.

I also sent you privately two XML samples which are perfect for testing the final layout. Both contain more or less all possible JATS elements, where one features mixed-citation and the other element-citation references so you can compare them in author mode as well. Please keep them private as they're part of our journal.

**Comment by futurion** [comment]
@raducoravu Maybe just one more thought in regards to references display in Author mode. A big amount of references nowadays feature two parameters "doi" and "pmid". The XML format is as follows:

`
<pub-id pub-id-type="doi">10.1212/WNL.0000000000002923</pub-id>
<pub-id pub-id-type="pmid">27371494</pub-id>
`

Would it be maybe possible to create actual links from them in author mode? The links are always the same, you just have to add prefixes, like this:

`
DOI: <a href="https://doi.org/{$doi-url}">
PMID: <a href="https://pubmed.ncbi.nlm.nih.gov/{$pmid-url}">
`

**Comment by raducoravu** [comment]
Thanks @futurion, we also got your samples and we'll try to find some time to look more into this.

**Comment by raducoravu** [comment]
I will close this issue and open a new one because the latest proposed changes are more like improvements over the existing rendering, not side effects of the pull request which added tables support.

**Comment by raducoravu** [comment]
We released Oxygen 23 yesterday along with the latest JATS framework fixes. Thanks @futurion for the feedback and @wendellpiez for the review.
