### ISSUE TITLE
Table related actions work only with Oxygen 22.1 and newer

### ISSUE THREAD

**Issue by raducoravu** [wendellpiez/JATSKit#51]
The addon is advertised to work with Oxygen 17 and newer. But recently in Oxygen 22.1 we upgraded the used logging system and the Java extensions used for the table related actions use the new type of logger, whose libraries are not part of Oxygen 22.0 and older.
My colleague Cosmin proposes a fix by adding the new logging libraries to the add-on:
https://github.com/wendellpiez/JATSKit/pull/50
I will also ask him to provide a NOTICES file to state there that the logging libraries (Apache 2.0 license) are distributed with the add-on.

**Comment by raducoravu** [comment]
@wendellpiez if you consider the fix in PR #50 ok, you can merge it in. Otherwise the add-on's table-related actions no longer work with older Oxygen versions.

**Comment by raducoravu** [comment]
The PR was accepted by @wendellpiez

**Comment by wendellpiez** [comment]
Radu is there a way we can mark the most recent commit that is considered to work well with oXygen 17, with a tag or something so that users can find it if needed?

I am fine on going forward with current version but I don't want to leave anyone behind either. There are many older versions of oXygen out there I think. Presumably it all works except the table actions?

**Comment by raducoravu** [comment]
In this case the problem was not discovered until the fix was integrated. If in the future we commit on purpose a change breaking the compatibility indeed we can tag the project before the PR is accepted, maybe add also an entry in the addon.xml for the older compatible add-on.

**Comment by wendellpiez** [comment]
@raducoravu if we found the problem and the users haven't reported any, we're good. Let me know if you think the docs should be adjusted (or I will try and remember to look).
