### ISSUE TITLE
Difficulties with the DOCX to JATS XML conversion 

### ISSUE THREAD

**Issue by pmoreno-DTP** [wendellpiez/JATSKit#57]
Currently, I'm testing various open-source solutions in order to implement a JATS XML publishing workflow, which includes the following steps:

1.	Creating the original file in DOCX format, adhering to a pre-defined stylesheet
2.	Pre-processing and converting the file from DOCX to JATS XML
3.	Validating the JATS XML file
4.	Converting the JATS XML file into XLIFF format for translation
5.	Translating and reviewing using CAT tools (e.g., RWS Trados Studio)
6.	Importing the translated content and generating the target JATS XML files
7.	Performing a final proofreading
8.	Publishing the original and translated documents in PDF, DOCX, and HTML formats

However, my coding experience is limited, and I'm facing difficulties with the DOCX to JATS XML conversion process. I can follow directions and can usually figure out programs. I also have **oXygen XML Editor**, but I'm still learning how to use it.

-- Could you please provide some tips or suggest the best approach to address this challenge? 

I look forward to your guidance and greatly appreciate any assistance you can provide.

**Comment by raducoravu** [comment]
Oxygen's support for DocX to JATS allows for this:
Open the DOCX in Word, select all, then paste inside a JATS document opened for visual editing in Oxygen and Oxygen should convert the pasted Word content to JATS.

Or you could try a converter like Pandoc to convert from the command line Word documents to Jats, I have not used it myself for this task but maybe you can experiment using it:
https://pandoc.org/index.html

**Comment by pmoreno-DTP** [comment]
What about using **meTypeset** (https://github.com/MartinPaulEve/meTypeset) or **DOCX2JATS** (https://github.com/Vitaliy-1/DOCX2JATS)? -- Has anyone ever used any of these options?

**Comment by raducoravu** [comment]
@pmoreno-DTP this is the GitHub issues list for an Oxygen framework for editing JATS. Maybe you can find a JATS-specific forum or users list where to ask these questions. Personally I am not familiar with both tools you mentioned. You can also try to test them on your content and see how that goes.

**Comment by pmoreno-DTP** [comment]
@raducoravu -- Thanks for your suggestion. I will try to find a JATS specific forum to ask these questions.
